name: Bsale Challenge - CI/CD FastApi AWS lambda

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9.23"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar tests (si tienes pytest)
        run: |
          pytest || echo "⚠️ No hay tests definidos"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.AWS_KEY }}

      - name: Copiar archivos al servidor
        run: |
          rsync -avz --exclude 'venv' ./ ${{ secrets.AWS_USER }}@${{ secrets.AWS_HOST }}:/home/${{ secrets.AWS_USER }}/bsale-challenge

      - name: Instalar dependencias en servidor
        run: |
          ssh ${{ secrets.AWS_USER }}@${{ secrets.AWS_HOST }} << 'EOF'
            cd ~/bsale-challenge
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
          EOF

      - name: Reiniciar servicio systemd
        run: |
          ssh ${{ secrets.AWS_USER }}@${{ secrets.AWS_HOST }} << 'EOF'
            sudo systemctl daemon-reload
            sudo systemctl restart bsale-challenge
            sudo systemctl status bsale-challenge --no-pager
          EOF
