name: Bsale Challenge - CI/CD FastApi AWS lambda

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9.23"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  deploy:
    runs-on: ubuntu-latest
    environment: Bsale-challenge 
    needs: build
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.AWS_KEY }}

      - name: Add remote host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.AWS_HOST }} >> ~/.ssh/known_hosts

      - name: Copiar archivos al servidor
        run: |
          rsync -avz  --exclude 'venv' ./ ${{ secrets.AWS_USER }}@${{ secrets.AWS_HOST }}:/opt/bsale-challenge-2025

      - name: Instalar dependencias en servidor
        run: |
          ssh ${{ secrets.AWS_USER }}@${{ secrets.AWS_HOST }} << 'EOF'
            cd /opt/bsale-challenge-2025
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
          EOF
      # Reiniciar servicio systemd
      - name: Reiniciar servicio systemd
        run: |
          ssh ${{ secrets.AWS_USER }}@${{ secrets.AWS_HOST }} << 'EOF'
            sudo systemctl daemon-reload
            sudo systemctl restart bsale-challenge
            sudo systemctl status bsale-challenge --no-pager
          EOF
